services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: milktea_sqlserver
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Passw0rd"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'YourStrong@Passw0rd' -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sqlserver_data:
    driver: local
